$(function () {
	$(".kemu1").click(function(){
      	$(".kecheng1").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
    	$("#triangle_border_up").css('left',' 97px');
    });
    $(".kemu2").click(function(){
      	$(".kecheng2").show(); 
      	$(".kecheng1").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
    	$("#triangle_border_up").css('left','219px');
    });
    $(".kemu3").click(function(){
      	$(".kecheng3").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng1").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
    	$("#triangle_border_up").css('left','333px');
    });
    $(".kemu4").click(function(){
      	$(".kecheng4").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng1").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
      	$("#triangle_border_up").css('left','466px');
    });
    $(".kemu5").click(function(){
      	$(".kecheng5").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng1").hide();
      	$(".kecheng6").hide();
      	$("#triangle_border_up").css('left','589px');
    });
    $(".kemu6").click(function(){
      	$(".kecheng6").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng1").hide();
      	$("#triangle_border_up").css('left','711px');
    });
    $(".teacherdown li").click(function(){
      	$(this).addClass("on").siblings().removeClass();
	});
	$("#teacher1").click(function(){
      	$("#teacher1").css('left','181px');
      	$("#teacher1").css('top','-70px');
      	$("#teacher2").css('left','405px');
      	$("#teacher2").css('top','65px');
      	$("#teacher3").css('left','405px');
      	$("#teacher3").css('top','315px');
      	$("#teacher4").css('left','181px');
      	$("#teacher4").css('top','440px');
      	$("#teacher5").css('left','-25px');
      	$("#teacher5").css('top','315px');
      	$("#teacher6").css('left','-25px');
      	$("#teacher6").css('top','65px');
      	$("#triangle_border_down").hide();
      	setTimeout(function() {
            $("#triangle_border_down").show();
        }, 1000)
      	$(".teacher1").show(); 
      	$(".teacher2").hide();
      	$(".teacher3").hide();
      	$(".teacher4").hide();
      	$(".teacher5").hide();
      	$(".teacher6").hide();
    });
    $("#teacher2").click(function(){
      	$("#teacher2").css('left','181px');
      	$("#teacher2").css('top','-70px');
      	$("#teacher3").css('left','405px');
      	$("#teacher3").css('top','65px');
      	$("#teacher4").css('left','405px');
      	$("#teacher4").css('top','315px');
      	$("#teacher5").css('left','181px');
      	$("#teacher5").css('top','440px');
      	$("#teacher6").css('left','-25px');
      	$("#teacher6").css('top','315px');
      	$("#teacher1").css('left','-25px');
      	$("#teacher1").css('top','65px');
      	$("#triangle_border_down").hide();
      	setTimeout(function() {
            $("#triangle_border_down").show();
        }, 1000)
      	$(".teacher2").show(); 
      	$(".teacher1").hide();
      	$(".teacher3").hide();
      	$(".teacher4").hide();
      	$(".teacher5").hide();
      	$(".teacher6").hide();
    });
    $("#teacher3").click(function(){
      	$("#teacher3").css('left','181px');
      	$("#teacher3").css('top','-70px');
      	$("#teacher4").css('left','405px');
      	$("#teacher4").css('top','65px');
      	$("#teacher5").css('left','405px');
      	$("#teacher5").css('top','315px');
      	$("#teacher6").css('left','181px');
      	$("#teacher6").css('top','440px');
      	$("#teacher1").css('left','-25px');
      	$("#teacher1").css('top','315px');
      	$("#teacher2").css('left','-25px');
      	$("#teacher2").css('top','65px');
      	$("#triangle_border_down").hide();
      	setTimeout(function() {
            $("#triangle_border_down").show();
        }, 1000)
      	$(".teacher3").show(); 
      	$(".teacher2").hide();
      	$(".teacher1").hide();
      	$(".teacher4").hide();
      	$(".teacher5").hide();
      	$(".teacher6").hide();
    });
    $("#teacher4").click(function(){
      	$("#teacher4").css('left','181px');
      	$("#teacher4").css('top','-70px');
      	$("#teacher5").css('left','405px');
      	$("#teacher5").css('top','65px');
      	$("#teacher6").css('left','405px');
      	$("#teacher6").css('top','315px');
      	$("#teacher1").css('left','181px');
      	$("#teacher1").css('top','440px');
      	$("#teacher2").css('left','-25px');
      	$("#teacher2").css('top','315px');
      	$("#teacher3").css('left','-25px');
      	$("#teacher3").css('top','65px');
      	$("#triangle_border_down").hide();
      	setTimeout(function() {
            $("#triangle_border_down").show();
        }, 1000)
      	$(".teacher4").show(); 
      	$(".teacher2").hide();
      	$(".teacher3").hide();
      	$(".teacher1").hide();
      	$(".teacher5").hide();
      	$(".teacher6").hide();
    });
    $("#teacher5").click(function(){
      	$("#teacher5").css('left','181px');
      	$("#teacher5").css('top','-70px');
      	$("#teacher6").css('left','405px');
      	$("#teacher6").css('top','65px');
      	$("#teacher1").css('left','405px');
      	$("#teacher1").css('top','315px');
      	$("#teacher2").css('left','181px');
      	$("#teacher2").css('top','440px');
      	$("#teacher3").css('left','-25px');
      	$("#teacher3").css('top','315px');
      	$("#teacher4").css('left','-25px');
      	$("#teacher4").css('top','65px');
  		$("#triangle_border_down").hide();
      	setTimeout(function() {
            $("#triangle_border_down").show();
        }, 1000)
      	$(".teacher5").show(); 
      	$(".teacher2").hide();
      	$(".teacher3").hide();
      	$(".teacher4").hide();
      	$(".teacher1").hide();
      	$(".teacher6").hide();
      	
    });
    $("#teacher6").click(function(){
      	$("#teacher6").css('left','181px');
      	$("#teacher6").css('top','-70px');
      	$("#teacher1").css('left','405px');
      	$("#teacher1").css('top','65px');
      	$("#teacher2").css('left','405px');
      	$("#teacher2").css('top','315px');
      	$("#teacher3").css('left','181px');
      	$("#teacher3").css('top','440px');
      	$("#teacher4").css('left','-25px');
      	$("#teacher4").css('top','315px');
      	$("#teacher5").css('left','-25px');
      	$("#teacher5").css('top','65px');
      	$("#triangle_border_down").hide();
      	setTimeout(function() {
            $("#triangle_border_down").show();
        }, 1000)
      	$(".teacher6").show(); 
      	$(".teacher2").hide();
      	$(".teacher3").hide();
      	$(".teacher4").hide();
      	$(".teacher5").hide();
      	$(".teacher1").hide();
    });
})