$(function () {
	$(".kemu1").click(function(){
      	$(".kecheng1").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
    	$("#triangle_border_up").css('left','60px');
    });
    $(".kemu2").click(function(){
      	$(".kecheng2").show(); 
      	$(".kecheng1").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
    	$("#triangle_border_up").css('left','146px');
    });
    $(".kemu3").click(function(){
      	$(".kecheng3").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng1").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
    	$("#triangle_border_up").css('left','224px');
    });
    $(".kemu4").click(function(){
      	$(".kecheng4").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng1").hide();
      	$(".kecheng5").hide();
      	$(".kecheng6").hide();
      	$("#triangle_border_up").css('left','319px');
    });
    $(".kemu5").click(function(){
      	$(".kecheng5").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng1").hide();
      	$(".kecheng6").hide();
      	$("#triangle_border_up").css('left','404px');
    });
    $(".kemu6").click(function(){
      	$(".kecheng6").show(); 
      	$(".kecheng2").hide();
      	$(".kecheng3").hide();
      	$(".kecheng4").hide();
      	$(".kecheng5").hide();
      	$(".kecheng1").hide();
      	$("#triangle_border_up").css('left','490px');
    });
})